# Build settings
build:
  folder_name: 'build'
  path: './build'

# Exclusion settings
exclude:
  files:
    - 'setup.py'
    - '__init__.py'
    - 'manage.py'
    - 'urls.py'
  dirs:
    - 'migrations'
    - '.venv'
    - 'cythonizer'
  copying_files:
    - '.env'
    - '.gitignore'
    - 'README.md'
  copying_dirs:
    - 'logs'
    - 'media'
    - 'static'
    - '.venv'
    - 'build'

# Logging settings
logging:
  dir: 'log'
  filename: 'build_log_{timestamp}.txt'

# Cython settings
cython:
  language_level: '3'

# Project settings
project:
  name: 'django_cython_project'
  version: '0.1'
  python_requires: '>=3.6'
  install_requires:
    - 'Django>=3.2'
    - 'Cython>=0.29'